site_name: All in Bits Onboarding
theme:
  logo: assets/aib-logo.png
  favicon: assets/favicon.png
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - header.autohide
    - toc.integrate
    - content.action.edit
    - content.action.view
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - awesome-pages
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: gnolang/guide
      branch: main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

extra:
  generator: false
  version:
    default: latest
    provider: mike

repo_url: https://github.com/gnolang/guide
repo_name: gnolang/guide
edit_uri: edit/main/docs/
